### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'level_num'

### ISSUE THREAD

**Issue by nashanghenzan** [bhattlab/kraken2_classification#28]
i successfully build kraken2 and bracken database , but when i ran bracken, it occur some error:
```
(base) [root@centos7-02-66b664b9d9-gz85w bin_library]# bracken \
> -d /mnt/shujuku/kraken2_MAG/bin_library \
> -i /mnt/semibin/quant/kraken/PHB.report \
> -r 150 \
> -o /mnt/semibin/quant/PHB \
> -w /mnt/semibin/quant/PHB.report
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i /mnt/semibin/quant/kraken/PHB.report -o /mnt/semibin/quant/PHB -k /mnt/shujuku/kraken2_MAG/bin_library/database150mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 04-29-2023 14:56:54
>> Checking report file: /mnt/semibin/quant/kraken/PHB.report
Traceback (most recent call last):
  File "/root/miniconda3/bin/src/est_abundance.py", line 554, in <module>
    main()
  File "/root/miniconda3/bin/src/est_abundance.py", line 291, in main
    while level_num != (prev_node.level_num + 1):
AttributeError: 'NoneType' object has no attribute 'level_num'
```

**Comment by bsiranosian** [comment]
This is an issue for the kraken/braken repo, not this pipeline.

**Comment by nashanghenzan** [comment]
> This is an issue for the kraken/braken repo, not this pipeline.

how to solve this issue？i try to ran a normal sample and database with bracken, it succeed. i use bracken because i want gain abundance of MAG in my sample.
